{% set name = "sqlmermaid" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlmermaid-{{ version }}.tar.gz
  sha256: 7bc49b0aed8bc1fd517859f3f0b8c8d074d575907f874501e044432d2af6d45a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=2.0.0

test:
  imports:
    - sqlmermaid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/endremborza/sqlmermaid
  summary: Visualizing SQL databases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
